---
- name: Add vscode yum repo
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code
    file: microsoft-vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: Install vscode
  ansible.builtin.package:
    name: code
    state: present
  become: true

- name: Ensure desktop directory exists
  ansible.builtin.file:
    path: ~/.local/share/applications
    state: directory
    mode: '0755'

- name: Copy desktop file with wayland support
  ansible.builtin.copy:
    src: code.desktop
    dest: ~/.local/share/applications/code.desktop
    mode: '0644'

- name: Install vscode extensions
  ansible.builtin.shell: set -o pipefail; code --list-extensions | grep {{ item }} || code --install-extension {{ item }} >/dev/null
  changed_when: "item not in result.stdout"
  with_items: "{{ extensions }}"
