---
- name: Incus yum repository
  ansible.builtin.yum_repository:
    name: copr:copr.fedorainfracloud.org:ganto:lxc4
    file: ganto-lxc4-incus
    description: Copr repo for lxc4 owned by ganto
    baseurl: https://download.copr.fedorainfracloud.org/results/ganto/lxc4/fedora-$releasever-$basearch/
    skip_if_unavailable: true
    gpgcheck: 1
    gpgkey: https://download.copr.fedorainfracloud.org/results/ganto/lxc4/pubkey.gpg
    repo_gpgcheck: 0
    enabled: 1
  become: true

- name: Install incus
  ansible.builtin.package:
    name: incus
    state: present
  become: true

- name: Gather incus preseed config
  ansible.builtin.command: "incus admin init --dump"
  register: result
  changed_when: false

- name: Pressed incus config
  ansible.builtin.command:
    cmd: "incus admin init --preseed"
    stdin: "{{ config | to_yaml(indent=4) }}"
  vars:
    config: "{{ incus_preseed_defaults | combine(incus_preseed_overrides, recursive=True, list_merge='append_rp') }}"
  changed_when: true
  when: (result.stdout | from_yaml) != config
  become: true

- name: Add incusbr0 to trusted zone
  ansible.posix.firewalld:
    zone: trusted
    interface: incusbr0
    permanent: true
    state: enabled
  become: true
