---
- name: Install libvirt packages
  ansible.builtin.package:
    name:
      - virt-install
      - virt-manager
      - virt-viewer
      - virt-top
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
    state: present
  become: true

- name: Enable libvirt services
  ansible.builtin.systemd:
    name: libvirtd
    enabled: true
  become: true
