---
- name: Run rpm-ostree status
  ansible.builtin.command: rpm-ostree status --json
  register: result
  changed_when: false

- name: Parse rpm-ostree status output
  ansible.builtin.set_fact:
    ostree_status: "{{ result.stdout | from_json }}"
