---
- name: Upgrade packages (dnf)
  ansible.builtin.dnf: # noqa package-latest
    name: "*"
    state: latest
  when:
    - pkg_upgrade
    - ansible_facts['pkg_mgr'] == "dnf"

- name: Upgrade packages (rpm-ostree)
  ansible.posix.rpm_ostree_upgrade:
  when:
    - pkg_upgrade
    - ansible_facts['pkg_mgr'] == "community.general.rpm_ostree_pkg"

- name: Remove rpm-ostree packages from base layer
  when:
    - ansible_facts['distribution'] == 'Fedora'
    - ansible_facts['pkg_mgr'] == "community.general.rpm_ostree_pkg"

  block:
    - name: Get rpm-ostree base packages for removal
      ansible.builtin.include_role:
        name: ostree-status

    - name: Get packages for removal
      ansible.builtin.set_fact:
        remove_packages: "{{ fedora_ostree_remove_packages | difference(ostree_status['deployments'][0]['requested-base-removals']) }}"

    - name: Remove ostree packages from base layer
      ansible.builtin.command: rpm-ostree override remove {{ remove_packages | join() }}
      changed_when: true
      when: remove_packages
      become: true
