---
- name: Install gpg2
  ansible.builtin.package:
    name: gnupg2
    state: present
  become: true

- name: Enable user systemd gpg sockets
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    scope: global
    enabled: true
  with_items:
    - gpg-agent.socket
    - gpg-agent-ssh.socket
    - gpg-agent-extra.socket
  become: true

- name: Enable ssh auth using gpg
  ansible.builtin.copy:
    content: |
      export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh"
    dest: "/etc/profile.d/gpg-ssh-auth.sh"
    mode: '0644'
  when: gpg_enable_ssh_auth
  become: true
