---
- name: Install extra gnome packages (fedora)
  ansible.builtin.package:
    name:
      - gnome-system-monitor
      - gnome-tweak-tool

      # TODO: install from source
      - gnome-shell-extension-pop-shell

      # needed by system-monitor-next extension
      - libgtop2-devel
      - NetworkManager-libnm-devel

      # desktop
      - gpaste
      - ulauncher

    state: present
  become: true
  when: ansible_facts['distribution'] == "Fedora"

- name: Install extra gnome extensions
  ansible.builtin.shell: set -o pipefail; gnome-extensions list | grep {{ item.key }} || gnome-extensions install {{ item.value }}
  register: result
  become: false
  changed_when: "item.key not in result.stdout"
  with_dict: "{{ install_extensions }}"

- name: Template gnome dconf settings
  ansible.builtin.template:
    src: dconf.ini
    dest: ~/.config/dconf.ini
    mode: "600"
  register: dconf_template
  become: false

- name: Load gnome dconf settings
  ansible.builtin.shell: set -o pipefail; dconf load -f / < {{ dconf_template.dest }}
  changed_when: dconf_template.changed
  become: false

- name: Enable gnome shell extensions
  ansible.builtin.shell: set -o pipefail; gnome-extensions list --enabled | grep {{ item }} || gnome-extensions enable {{ item }}
  register: result
  changed_when: "item not in result.stdout"
  with_items: '{{ gnome_enable_extensions }}'
  become: false

- name: Disable gnome shell extensions
  ansible.builtin.shell: set -o pipefail; gnome-extensions list --disabled | grep {{ item }} || gnome-extensions disable {{ item }}
  register: result
  changed_when: "item not in result.stdout"
  with_items: '{{ gnome_disable_extensions }}'
  become: false

- name: Enable ulauncher autostart
  ansible.builtin.file:
    src: /usr/share/applications/ulauncher.desktop
    dest: ~/.config/autostart/ulauncher.desktop
    state: link
  become: false
