---
- name: Install qemu
  ansible.builtin.package:
    name:
      - qemu-kvm
      - qemu-img

      # UEFI firmware
      - edk2-ovmf
      - edk2-aarch64
    state: present
  become: true

- name: Copy aarch64 ovmf code
  ansible.builtin.copy:
    src: /usr/share/edk2/aarch64/QEMU_EFI-silent-pflash.raw
    dest: /usr/share/edk2/ovmf/OVMF_CODE.fd
    remote_src: true
    backup: true
    mode: '0644'
  become: true
  when: ansible_architecture == "aarch64"

# - name: Create aarch64 ovmf vars
#   command:
#     cmd: qemu-img resize -f raw
