---
- name: Install printing packages
  ansible.builtin.package:
    name: "{{ packages | select() | list }}"
    state: present
  vars:
    packages:
      - hplip
      - "{{ printing_enable_gui | ternary('hplip-gui', '') }}"
      - "{{ printing_enable_gui | ternary('simple-scan', '') }}"
  become: true

# - name: Try to install hplip-plugin
#   ansible.builtin.package:
#     name: hplip-plugin
#     state: present
#   become: true
#   ignore_errors: true

# - name: Gather the rpm package facts
#   package_facts:
#     manager: auto

- name: Print packages
  ansible.builtin.debug:
    var: ansible_facts.packages

- name: Ensure hp directory exists
  ansible.builtin.file:
    path: /var/lib/hp
    state: directory
    mode: '0755'
  become: true

# - name: Copy hplip-plugin state file
#   ansible.builtin.template:
#     src: hp/hplip.state.j2
#     dest: /var/lib/hp/hplip.state
#     mode: "744"
#   vars:
#     hplip_version: "{{ ansible_facts.packages['hplip'].version.split('.')[0:3] | join('.') }}"
#   when: "'hplip' in ansible_facts.packages"
#   become: true

- name: Copy additional hp udev rules
  ansible.builtin.copy:
    src: hp_lt4110.rules
    dest: /etc/udev/rules.d/99-hp_lt4110.rules
    mode: '0644'
  become: true
