---
- name: Update Grub2 config file fedora
  become: true
  ansible.builtin.command: grub2-mkconfig -o {{ grub_cmdline_config }}
  changed_when: false

- name: Update Grub2 config file ubuntu
  become: true
  ansible.builtin.command: /usr/sbin/update-grub
  changed_when: false
