---
- name: Install flatpak
  ansible.builtin.package:
    name: flatpak
    state: present
  become: true

- name: Add flathub remotes
  community.general.flatpak_remote:
    name: "{{ item.key }}"
    state: present
    flatpakrepo_url: "{{ item.value }}"
    method: user
  with_dict: "{{ flatpak_remotes }}"

- name: Upgrade all flatpaks
  ansible.builtin.command: flatpak update --user --noninteractive
  register: flatpak_update_output
  changed_when: "'app/' in flatpak_update_output.stdout"
  when: pkg_upgrade

- name: Ensure flatpak overrides directory exists
  ansible.builtin.file:
    path: ~/.local/share/flatpak/overrides
    state: directory
    mode: '0755'

- name: Install Flatpak overrides
  ansible.posix.synchronize:
    src: overrides
    dest: ~/.local/share/flatpak/overrides

- name: Ensure flatpak files directory exists
  ansible.builtin.file:
    path: ~/.local/share/flatpak/files
    state: directory
    mode: '0755'

- name: Install Flatpak files
  ansible.posix.synchronize:
    src: extra_files
    dest: ~/.local/share/flatpak/files
