version: "3.5"

services:
  traefik:
    container_name: traefik
    image: "{{traefik_image}}"
    ports:
      - "80:80"
      - "443:443"
      # remove port 8080 for production
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/traefik/config:/etc/traefik
      - /srv/traefik/ssl:/ssl-certs/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge