version: "3.5"

services:

  netmaker:
    container_name: netmaker
    image: gravitl/netmaker:$SERVER_IMAGE_TAG
    env_file: ./netmaker.env
    restart: always
    volumes:
      - dnsconfig:/root/config/dnsconfig
      - sqldata:/root/data
    environment:
      # config-dependant vars
      - STUN_LIST=stun1.netmaker.io:3478,stun2.netmaker.io:3478,stun1.l.google.com:19302,stun2.l.google.com:19302
      # The domain/host IP indicating the mq broker address
      - BROKER_ENDPOINT=wss://broker.${NM_DOMAIN}
      # The base domain of netmaker
      - SERVER_NAME=${NM_DOMAIN}
      - SERVER_API_CONN_STRING=api.${NM_DOMAIN}:443
      # Address of the CoreDNS server. Defaults to SERVER_HOST
      - COREDNS_ADDR=${SERVER_HOST}
      # Overrides SERVER_HOST if set. Useful for making HTTP available via different interfaces/networks.
      - SERVER_HTTP_HOST=api.${NM_DOMAIN}
      # domain for your turn server
      - TURN_SERVER_HOST=turn.${NM_DOMAIN}
      # domain of the turn api server
      - TURN_SERVER_API_HOST=https://turnapi.${NM_DOMAIN}
    networks:
      - netmaker
    labels:
      - traefik.enable=true
      - traefik.http.routers.netmaker-api.entrypoints=websecure
      - traefik.http.routers.netmaker-api.rule=Host(`api.${NM_DOMAIN}`)
      - traefik.http.routers.netmaker-api.service=netmaker-api
      - traefik.http.services.netmaker-api.loadbalancer.server.port=8081

  netmaker-ui:
    container_name: netmaker-ui
    image: gravitl/netmaker-ui:$UI_IMAGE_TAG
    env_file: ./netmaker.env
    environment:
      # config-dependant vars
      # URL where UI will send API requests. Change based on SERVER_HOST, SERVER_HTTP_HOST, and API_PORT
      BACKEND_URL: "https://api.${NM_DOMAIN}"
    depends_on:
      - netmaker
    links:
      - "netmaker:api"
    restart: always
    networks:
      - netmaker
    labels:
      - traefik.enable=true
      - traefik.http.routers.netmaker-ui-http.entrypoints=web
      - traefik.http.routers.netmaker-ui-http.rule=Host(`dashboard.${NM_DOMAIN}`)
      - traefik.http.middlewares.nmui-security.headers.accessControlAllowOriginList=*.${NM_DOMAIN}
      - traefik.http.middlewares.nmui-security.headers.stsSeconds=31536000
      - traefik.http.middlewares.nmui-security.headers.browserXssFilter=true
      - traefik.http.middlewares.nmui-security.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.nmui-security.headers.customResponseHeaders.X-Robots-Tag=none
      - traefik.http.middlewares.nmui-security.headers.customResponseHeaders.Server= # Remove the server name
      - traefik.http.routers.netmaker-ui.middlewares=nmui-security@docker
      - traefik.http.routers.netmaker-ui.entrypoints=websecure
      - traefik.http.routers.netmaker-ui.rule=Host(`dashboard.${NM_DOMAIN}`)
      - traefik.http.routers.netmaker-ui.service=netmaker-ui
      - traefik.http.services.netmaker-ui.loadbalancer.server.port=80

  coredns:
    container_name: coredns
    image: coredns/coredns
    command: -conf /root/dnsconfig/Corefile
    env_file: ./netmaker.env
    depends_on:
      - netmaker
    restart: always
    volumes:
      - dnsconfig:/root/dnsconfig
    networks:
      - netmaker

  mq:
    container_name: mq
    image: eclipse-mosquitto:2.0.15-openssl
    env_file: ./netmaker.env
    depends_on:
      - netmaker
    restart: unless-stopped
    command: [ "/mosquitto/config/wait.sh" ]
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./wait.sh:/mosquitto/config/wait.sh
      - mosquitto_logs:/mosquitto/log
      - mosquitto_data:/mosquitto/data
    networks:
      - netmaker
    labels:
      - traefik.enable=true
      - traefik.http.routers.netmaker-broker.entrypoints=websecure
      - traefik.http.routers.netmaker-broker.rule=Host(`broker.${NM_DOMAIN}`)
      - traefik.http.routers.netmaker-broker.service=netmaker-broker
      - traefik.http.routers.netmaker-broker.middlewares=netmaker-broker-sslheader
      - traefik.http.services.netmaker-broker.loadbalancer.server.port=8883
      - traefik.http.services.netmaker-broker.loadBalancer.sticky.cookie=true
      - traefik.http.middlewares.netmaker-broker-sslheader.headers.customrequestheaders.X-Forwarded-Proto=https

  turn:
    container_name: turn
    image: gravitl/turnserver:latest
    env_file: ./netmaker.env
    environment:
      # config-dependant vars
      - USERNAME=${TURN_USERNAME}
      - PASSWORD=${TURN_PASSWORD}
      # domain for your turn server
      - TURN_SERVER_HOST=turn.${NM_DOMAIN}
    network_mode: "host"
    volumes:
      - turn_server:/etc/config
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.netmaker-turn.entrypoints=websecure
      - traefik.http.routers.netmaker-turn.rule=Host(`turn.${NM_DOMAIN}`)
      - traefik.http.routers.netmaker-turn.service=netmaker-turn
      - traefik.http.services.netmaker-turn.loadbalancer.server.port=3479
      - traefik.http.routers.netmaker-turnapi.entrypoints=websecure
      - traefik.http.routers.netmaker-turnapi.rule=Host(`turnapi.${NM_DOMAIN}`)
      - traefik.http.routers.netmaker-turnapi.service=netmaker-turnapi
      - traefik.http.services.netmaker-turnapi.loadbalancer.server.port=8089

volumes:
  sqldata: { }
  dnsconfig: { } # storage for coredns
  mosquitto_logs: { } # storage for mqtt logs
  mosquitto_data: { } # storage for mqtt data
  turn_server: { }

networks:
  netmaker:
    external:
      name: proxy