---
- name: check if firefox profile '{{profile}}' exists
  stat: 
    path: ~/.mozilla/firefox/{{ profile }}
  register: firefox_profile_exists

- name: Create firefox profile {{ profile }} if it does not exist
  shell: flatpak run --filesystem=~/.mozilla {{ firefox_flatpak_package }} -CreateProfile "{{ profile }} ~/.mozilla/firefox/{{ profile }}"
  environment:
    WAYLAND_DISPLAY: wayland-0
  when: not firefox_profile_exists.stat.exists

- name: Create firefox {{ profile }} profile desktop file
  template:
    src: firefox.desktop
    dest: ~/.local/share/applications/{{ desktop_file }}
    mode: u=rw,g=rw,o=r

- name: Install addons for {{ profile }}
  firefox_addon:
    url: https://addons.mozilla.org/en-US/firefox/addon/{{addon}} 
    state: present
    profile: "{{ansible_env.HOME}}/.mozilla/firefox/{{ profile }}" # wants a fullpath here
  tags: firefox-addons
  when: "'https://' not in addon"
  loop_control:
    loop_var: "addon"
  with_items: "{{ addons }}"

- name: Install firefox addons for {{ profile }} by url
  firefox_addon:
    url: "{{ addon }}"
    state: present
    profile: "{{ansible_env.HOME}}/.mozilla/firefox/{{ profile }}" # wants a fullpath here
  tags: firefox-addons
  when: "'https://' in addon"
  loop_control:
    loop_var: "addon"
  with_items: "{{ addons }}"

- name: ensure chrome directory exists
  file:
    path: ~/.mozilla/firefox/{{ profile }}/chrome
    state: directory

- name: Install userChrome.css
  template:
    src: userChrome.css
    dest: "~/.mozilla/firefox/{{ profile }}/chrome/userChrome.css"
    mode: u=rw,g=r,o=r

- name: Install user.js
  template:
    src: user.js
    dest: ~/.mozilla/firefox/{{ profile }}/user.js
    mode: u=rw,g=r,o=r
