---
- name: check if firefox profile '{{profile}}' exists
  stat: 
    path: "{{ansible_env.HOME}}/.mozilla/firefox/{{ profile }}"
  register: firefox_profile_exists

- name: Create firefox profile {{ profile }} if it does not exist
  shell: 'flatpak run --filesystem=~/.mozilla org.mozilla.firefox -CreateProfile "{{ profile }} {{ansible_env.HOME}}/.mozilla/firefox/{{ profile }}"'
  environment:
    WAYLAND_DISPLAY: wayland-0
  when: not firefox_profile_exists.stat.exists

- name: Create firefox {{ profile }} profile desktop file
  template:
    src: org.mozilla.firefox.desktop.j2
    dest: ~/.local/share/applications/{{ desktop_file }}
    mode: "440"

- name: Install addons for {{ profile }}
  firefox_addon:
    url: https://addons.mozilla.org/en-US/firefox/addon/{{addon}}
    state: present
    profile: "{{ansible_env.HOME}}/.mozilla/firefox/{{ profile }}"
  tags: firefox-addons
  when: "'https://' not in addon"
  loop_control:
    loop_var: "addon"
  with_items: "{{ addons }}"

- name: Install firefox addons for {{ profile }} by url
  firefox_addon:
    url: "{{ addon }}"
    state: present
    profile: "{{ansible_env.HOME}}/.mozilla/firefox/{{ profile }}"
  tags: firefox-addons
  when: "'https://' in addon"
  loop_control:
    loop_var: "addon"
  with_items: "{{ addons }}"

- name: ensure chrome directory exists
  file:
    path: "{{ansible_env.HOME}}/.mozilla/firefox/{{ profile }}/chrome"
    state: directory

- name: Install userChrome.css
  ansible.builtin.template:
    src: "{{ role_path }}/files/firefox/userChrome.css.j2"
    dest: "{{ansible_env.HOME}}/.mozilla/firefox/{{ profile }}/chrome/userChrome.css"
    mode: u=rw,g=r,o=r

- name: Install user.js
  ansible.builtin.template:
    src: "{{ role_path }}/files/firefox/user.js.j2"
    dest: "{{ansible_env.HOME}}/.mozilla/firefox/{{ profile }}/user.js"
    mode: u=rw,g=r,o=r
