---
- name: Install firefox flatpak package
  community.general.flatpak:
    remote: fedora # we use fedora remote, as it supports aarch64
    name: org.mozilla.Firefox
    state: present
    method: user

- name: Ensure firefox directory exists
  file:
    path: "~/.mozilla/firefox"
    state: directory

- name: Ensure desktop directory exists
  file:
    path: "~/.local/share/applications"
    state: directory

- name: Create firefox profiles
  include_tasks:
    file: ff-profile.yml
    apply:
      vars:
        name: "{{ item.value.name | default('Firefox ' + item.key) }}"
        profile: "{{ item.key }}"
        addons: "{{ firefox_addons + (item.value.addons | default([])) }}"
        desktop_file: "{{ item.value.desktop | default('org.mozilla.Firefox.' + item.key +'.desktop')}}"
        options: "{{ item.value.options | default({}) }}"
  with_dict: "{{ firefox_profiles }}"
