---
- name: Install firefox flatpak package
  community.general.flatpak:
    remote: fedora
    name: firefox
    state: present

- name: Ensure flatpak overrides directory exists
  file:
    path: ~/.local/share/flatpak/overrides
    state: directory

- name: Install firefox Flatpak override
  copy:
    src: org.mozilla.firefox
    dest: ~/.local/share/flatpak/overrides/org.mozilla.firefox

- name: Ensure firefox directory exists
  file:
    path: "~/.mozilla/firefox"
    state: directory

- name: Ensure desktop directory exists
  file:
    path: "~/.local/share/applications"
    state: directory

- name: Create firefox profiles
  include_tasks:
    file: ff-profile.yml
    apply:
      vars:
        name: "{{ item.value.name | default('Firefox ' + item.key) }}"
        profile: "{{ item.key }}"
        addons: "{{ addons + (item.value.addons | default([])) }}"
        desktop_file: "{{ item.value.desktop | default('org.mozilla.firefox.' + item.key +'.desktop')}}"
        options: "{{ item.value.options | default({}) }}"
  with_dict: "{{ profiles }}"
