---
- name: Add 1password repo
  yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    enabled: 1
    gpgcheck: 0
    repo_gpgcheck: 0
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
  become: yes 
  when: ansible_facts['distribution'] == "Fedora"

- name: Install 1password
  package:
    name: 1password
    state: present
  become: yes
