---
- name: Set install source (running on ARM)
  ansible.builtin.set_fact:
    onepassword_install_binary: true
  when: ansible_architecture == "aarch64"

- name: Install 1password (using pacakge)
  ansible.builtin.include_tasks:
    file: install-pkg.yml
    apply:
      become: true
  when: not onepassword_install_binary

- name: Install 1password (using binary)
  ansible.builtin.include_tasks:
    file: install-binary.yml
    apply:
      become: true
  when: onepassword_install_binary
