---
- name: Download traefik
  ansible.builtin.unarchive:
    src: https://github.com/traefik/traefik/releases/download/v{{traefik_version}}/traefik_v{{traefik_version}}_linux_arm64.tar.gz
    dest: /usr/local/bin
    include: ["traefik"]
    remote_src: true
    group: root
    owner: root
    mode: 0755

- name: Create traefik group
  ansible.builtin.group:
    name: traefik
    state: present

- name: Create traefik user
  ansible.builtin.user:
    name: traefik
    groups: traefik,docker
    shell: /sbin/nologin
    append: yes
    state: present
    create_home: no

- name: Create config directory
  ansible.builtin.file:
    path: /etc/traefik
    state: directory
    owner: traefik
    group: traefik
    mode: 0766

- name: Create directory for access logs
  ansible.builtin.file:
    path: /var/log/traefik
    state: directory
    owner: traefik
    group: traefik
    mode: 0766

- name: Copy traefik configuration
  ansible.builtin.copy:
    content: "{{ traefik_defaults | combine(traefik_config, recursive=true) | to_nice_yaml }}"
    dest: /etc/traefik/traefik.yaml
    owner: traefik
    group: traefik
    mode: 0644

- name: Copy traefik dynamic configuration
  ansible.builtin.copy:
    content: "{{ traefik_dynamic_config | to_nice_yaml }}"
    dest: /etc/traefik/traefik-dynamic.yaml
    owner: traefik
    group: traefik
    mode: 0644

- name: Create systemd service
  ansible.builtin.template:
    src: traefik.service.j2
    dest: /lib/systemd/system/traefik.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload traefik
