---
- name: Install chromium flatpak package
  community.general.flatpak:
    remote: flathub
    name: "{{ flatpak_package }}"
    state: present
    method: user

- name: Ensure ~/.config directory exists
  file:
    path: ~/.var/app/{{ flatpak_package }}/config
    state: directory

- name: Copy chromium-flags.conf
  copy:
    src: chromium-flags.conf
    dest: ~/.var/app/{{ flatpak_package }}/config/chromium-flags.conf
